###sign up
POST http://localhost:3000/authentication/sign-up 
Content-Type: application/json

{"email": "aaaa@gmail.com",
"password": "123456",
"firstName": "aaaa",
"lastName": "aaaa",
"phone": "1234567899"}


###sign in without 2fa
POST http://localhost:3000/authentication/sign-in
Content-Type: application/json

{
    "email": "aaaa@gmail.com",
    "password": "123456"
}

###sign in with 2fa
POST http://localhost:3000/authentication/sign-in
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "123456",
    "tfaCode": "884444"

}


###2fa
POST http://localhost:3000/authentication/2fa/generate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA5NzYzNzM4LCJleHAiOjE3MDk4NTAxMzgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.q99nfMEeBBUetFMR5NrZ6zhVSHfjveuJGt-JgULH-RM


###refresh token
POST http://localhost:3000/authentication/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTcwOTc1OTYxNiwiZXhwIjoxNzA5OTMyNDE2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.HKtO3av11s3gqkjxIphQRzed4VABUl9qDESdY5phQvQ"
}

###get user
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I

### update user
PATCH http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzE0Mjk5MTI4LCJleHAiOjE3MTQzODU1MjgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.P0_fGQtV0SKmEZt67pZxL35-RxJoN3HaKycKKV65TNs

{
    "firstName": "bla",
    "email": "bla@gmail.com"
}

### get links
GET http://localhost:3000/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I

### get link
GET http://localhost:3000/links/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I

### create link
POST http://localhost:3000/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I
Content-Type: application/json

{
  "title": "my link",
  "url": "https://www.facebook.com/",
  "price": 10,
  "isActive": true,
  "maxDownloadCount": 10
}

### update link
PATCH http://localhost:3000/links/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I
Content-Type: application/json

{
  "title": "string",
  "url": "https://www.facebook.com/",
  "price": 1,
  "expirationDate": "string",
  "isActive": false,
  "maxDownloadCount": 1
}

### delete link
DELETE http://localhost:3000/links/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3MTQ0NjYxMDIsImV4cCI6MTcxNDU1MjUwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TqMe3dMEQib7_mU-t5xBoS_ZoFpwI6X8tzY7wsor70I
